name: flow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  app_usage: ^4.0.1
  device_apps: ^2.2.0
  permission_handler: ^11.3.1
  numberpicker: ^2.1.2
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  usage_stats: ^1.3.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/